name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: zulu
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.2
      - name: Setup Maven caching
        uses: actions/cache@v2
        with:
          path: ~/.m2/**
          key: maven_deps
      - name: Build and test
        run: mvn clean test
